apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-gl-456
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/yangcao/codegen-gl-456:20592adfee1104a2274885fe3819ddbca0d213af@sha256:c8d48a0ac42f827b6fd59736fbb72313d977fbf1967e05ff934fe614fad10092 # use pre-built to bootstrap 
          name: app-inference
