apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-gl-456
  janus-idp.io/tekton: codegen-gl-456
  backstage.io/kubernetes-id: codegen-gl-456
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: codegen-gl-456
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml