kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen-gl-456-dsp-job-role
  annotations:
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - update
    apiGroups:
      - ""
    resources:
      - namespaces